<a href="https://colab.research.google.com/github/npqace/AIO2024-Exercise/blob/feature%2Fm2-w1-numpy/m2_w1_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy cơ bản

In [1]:
# cau 1
import numpy as np
arr = np.arange(0, 10, 1)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [2]:
# cau 2
arr = np.ones((3, 3)) >0
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [3]:
arr = np.ones((3, 3), dtype=bool)
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [4]:
arr = np.full((3, 3), fill_value=True, dtype=bool)
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [5]:
# cau 3
arr = np.arange(0, 10)
print(arr[arr % 2 == 1])

[1 3 5 7 9]


In [6]:
# cau 4
arr = np.arange(0, 10)
arr[arr % 2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [7]:
# cau 5
arr = np.arange(10)
arr_2d = arr.reshape(2, -1)
print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [8]:
# cau 6
arr1 = np.arange(10).reshape(2, -1)
arr2 = np.repeat(1, 10).reshape(2, -1)
c = np.concatenate([arr1, arr2], axis=0)
print("Result: \n", c)

Result: 
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [9]:
# cau 7
arr1 = np.arange(10).reshape(2, -1)
arr2 = np.repeat(1, 10).reshape(2, -1)
c = np.concatenate([arr1, arr2], axis=1)
print("C = ", c)

C =  [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [10]:
# cau 8
arr = np.array([1, 2, 3])
print(np.repeat(arr, 3))
print(np.tile(arr, 3))

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


In [11]:
# cau 9
a = np.array([2, 6, 1, 9, 10, 3, 27])
index = np.where((a>=5) & (a<=10))
print("result", a[index])

result [ 6  9 10]


In [12]:
# cau 10
def maxx(x, y):
    if x >= y:
        return x
    else:
        return y

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max = np.vectorize(maxx, otypes=[float])
print(pair_max(a, b))

[6. 7. 9. 8. 9. 7. 5.]


In [13]:
# cau 11
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

print("Result", np.where(a<b, b, a))

Result [6 7 9 8 9 7 5]


# Xử lý ảnh



In [15]:
# cau 12
!gdown 1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB

import matplotlib.image as mpimg
img = mpimg.imread('/content/dog.jpeg')
gray_img_01 = (np.max(img, axis=2) + np.min(img, axis=2)) / 2
gray_img_01[0, 0]

Downloading...
From: https://drive.google.com/uc?id=1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB
To: /content/dog.jpeg
100% 33.7k/33.7k [00:00<00:00, 59.8MB/s]


102.5

In [16]:
#  cau 13
gray_img_02 = np.mean(img, axis=2)
gray_img_02[0, 0]

107.66666666666667

In [17]:
#  cau 14
gray_img_03 = 0.21 * img[:, :, 0] + 0.72 * img[:, :, 1] + 0.07 * img[:, :, 2]
gray_img_03[0, 0]

126.22999999999999

# Phân tích dữ liệu dạng bảng



In [20]:
# download data
!gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq

import pandas as pd
df = pd.read_csv('/content/advertising.csv')

data = df.to_numpy()

Downloading...
From: https://drive.google.com/uc?id=1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
To: /content/advertising.csv
100% 4.06k/4.06k [00:00<00:00, 11.4MB/s]


In [27]:
# cau 15
max_sales = df['Sales'].max()
max_sales_index = df['Sales'].idxmax()
print(f"Max: {max_sales} - Index: {max_sales_index}")

Max: 27.0 - Index: 175


In [28]:
# cau 16
tv_avg = df['TV'].mean()
print(tv_avg)

147.0425


In [32]:
# cau 17
sales_from_20 = df[df['Sales'] >= 20].shape[0]
print(sales_from_20)

40


In [33]:
# cau 18
radio_avg = df[df['Sales'] >= 15]['Radio'].mean()
print(radio_avg)

26.22293577981651


In [35]:
# cau 19
news_avg = df['Newspaper'].mean()
sales_sum = df[df['Newspaper'] > news_avg]['Sales'].sum()
print(sales_sum)

1405.1


In [37]:
# cau 20
sales_avg = df['Sales'].mean()
scores = ['Good' if sale > sales_avg else
          'Bad' if sale < sales_avg else
          'Average'
          for sale in df['Sales']]
print(scores[7:10])

['Bad', 'Bad', 'Good']


In [43]:
# cau 21
closest_to_avg = df['Sales'].iloc[(df['Sales'] - sales_avg).abs().argmin()]
scores = ['Good' if sale > closest_to_avg else
          'Bad' if sale < closest_to_avg else
          'Average'
          for sale in df['Sales']]
print(scores[7:10])

['Bad', 'Bad', 'Good']
